// import './instance/index'
// import './lifecircle/index'
// import './data-binding/index'
// import './computed/index'
// import './directive/index'
// import './components/index'
import './features/index'
